name: OBD CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Lst files in runner
      - name: List repo files
        run: |
          pwd
          ls -la

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run tests
        run: |
          python -m unittest discover tests/

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t obd-project .

      # Log in to AWS ECR
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: ${{ secrets.AWS_REGION }}

      # Tag Docker image for ECR
      - name: Tag Docker image
        run: |
          docker tag obd-project:latest ${{ secrets.ECR_REPOSITORY }}:latest

      # Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
